var brand_MainBrandPick;
brand_MainBrandPick = "";
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=manet01&gaparam=street_brandpick_1'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2411_mainBrandPick.jpg' alt='브랜드Pick1' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=manet01&gaparam=street_brandpick_1'>MANET</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 좋아하는것을 함께 나누고 싶은 마음</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=arenazz&gaparam=street_brandpick_2'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2412_mainBrandPick.jpg' alt='브랜드Pick2' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=arenazz&gaparam=street_brandpick_2'>Blooming&me</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 작지만 따뜻한 아름다움을 전할 수 있는 것</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=LIVEWORK&gaparam=street_brandpick_3'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2413_mainBrandPick.jpg' alt='브랜드Pick3' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=LIVEWORK&gaparam=street_brandpick_3'>LIVEWORK</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 일상 속의 작은 감성</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=disney10x10&gaparam=street_brandpick_4'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2414_mainBrandPick.jpg' alt='브랜드Pick4' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=disney10x10&gaparam=street_brandpick_4'>Disney Edition</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 디즈니의 빈티지 감성을 통해 추억과 향수를 불러일으키는 것</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
document.write(brand_MainBrandPick);
