var brand_MainInterView;
brand_MainInterView = "";
brand_MainInterView+="<div class='swiper-slide' id='a01' onclick=location.href='http://www.10x10.co.kr/street/street_brand_sub02.asp?makerid=papersaladday&sid=i&sidx=52&gaparam=street_interview_1'>"
brand_MainInterView+="	<p><img src='http://imgstatic.10x10.co.kr/brandstreet/interview/201405/mainimg20140509174130.JPEG' width='442' height='360' alt='I am a Designer #8' /></p>"
brand_MainInterView+="	<dl class='account'>"
brand_MainInterView+="		<dt>PAPER SALAD DAY</dt>"
brand_MainInterView+="		<dd>"
brand_MainInterView+="			<p>감성 브랜드 페이퍼 샐러드 데이</p>"
brand_MainInterView+="		</dd>"
brand_MainInterView+="	</dl>"
brand_MainInterView+="</div>"
brand_MainInterView+="<div class='swiper-slide' id='a02' onclick=location.href='http://www.10x10.co.kr/street/street_brand_sub02.asp?makerid=circusboyband&sid=i&sidx=48&gaparam=street_interview_2'>"
brand_MainInterView+="	<p><img src='http://imgstatic.10x10.co.kr/brandstreet/interview/201312/mainimg20131216110312.JPEG' width='442' height='360' alt='I am a Designer #8' /></p>"
brand_MainInterView+="	<dl class='account'>"
brand_MainInterView+="		<dt>다양한 컬러를 연주하는 서커스보이밴드</dt>"
brand_MainInterView+="		<dd>"
brand_MainInterView+="			<p>함께 즐거워질 수 있는 매일매일을 생각합니다.</p>"
brand_MainInterView+="		</dd>"
brand_MainInterView+="	</dl>"
brand_MainInterView+="</div>"
brand_MainInterView+="<div class='swiper-slide' id='a03' onclick=location.href='http://www.10x10.co.kr/street/street_brand_sub02.asp?makerid=iconic&sid=i&sidx=49&gaparam=street_interview_3'>"
brand_MainInterView+="	<p><img src='http://imgstatic.10x10.co.kr/brandstreet/interview/201312/mainimg20131223140927.JPEG' width='442' height='360' alt='I am a Designer #8' /></p>"
brand_MainInterView+="	<dl class='account'>"
brand_MainInterView+="		<dt> ICON OF ALL YOURS</dt>"
brand_MainInterView+="		<dd>"
brand_MainInterView+="			<p>당신을 표현하는 또 하나의 이미지</p>"
brand_MainInterView+="		</dd>"
brand_MainInterView+="	</dl>"
brand_MainInterView+="</div>"
document.write(brand_MainInterView);
