var brand_MainLookBook;
brand_MainLookBook = "";
brand_MainLookBook+="<div class='swiper-slide' style='cursor:pointer;' onclick=location.href='http://www.10x10.co.kr/street/street_brand_sub05.asp?makerid=weweplanet&sid=l&sidx=96'>"
brand_MainLookBook+="	<div class='bInfo'>"
brand_MainLookBook+="		<dl>"
brand_MainLookBook+="			<dt>wewe</dt>"
brand_MainLookBook+="			<dd><p>WE CAN MAKE A BETTR PLANET</p></dd>"
brand_MainLookBook+="		</dl>"
brand_MainLookBook+="	</div>"
brand_MainLookBook+="	<div class='pic'><img src='http://imgstatic.10x10.co.kr/brandstreet/lookbook/201509/mainimg20150921100422.JPEG' width='259' height='360' alt='wewe' /></div>"
brand_MainLookBook+="</div>"
brand_MainLookBook+="<div class='swiper-slide' style='cursor:pointer;' onclick=location.href='http://www.10x10.co.kr/street/street_brand_sub05.asp?makerid=mtCASA&sid=l&sidx=65'>"
brand_MainLookBook+="	<div class='bInfo'>"
brand_MainLookBook+="		<dl>"
brand_MainLookBook+="			<dt>mt CASA</dt>"
brand_MainLookBook+="			<dd><p>MAKING IS FUN! </p></dd>"
brand_MainLookBook+="		</dl>"
brand_MainLookBook+="	</div>"
brand_MainLookBook+="	<div class='pic'><img src='http://imgstatic.10x10.co.kr/brandstreet/lookbook/201404/mainimg20140408113317.JPEG' width='259' height='360' alt='mt CASA' /></div>"
brand_MainLookBook+="</div>"
brand_MainLookBook+="<div class='swiper-slide' style='cursor:pointer;' onclick=location.href='http://www.10x10.co.kr/street/street_brand_sub05.asp?makerid=toms001&sid=l&sidx=56'>"
brand_MainLookBook+="	<div class='bInfo'>"
brand_MainLookBook+="		<dl>"
brand_MainLookBook+="			<dt>TOMS</dt>"
brand_MainLookBook+="			<dd><p>탐스</p></dd>"
brand_MainLookBook+="		</dl>"
brand_MainLookBook+="	</div>"
brand_MainLookBook+="	<div class='pic'><img src='http://imgstatic.10x10.co.kr/brandstreet/lookbook/201403/mainimg20140312135253.JPEG' width='259' height='360' alt='TOMS' /></div>"
brand_MainLookBook+="</div>"
document.write(brand_MainLookBook);
