var brand_MainBrandPick;
brand_MainBrandPick = "";
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=YURTSTUDIO'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/1529_mainBrandPick.jpg' alt='브랜드Pick1' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=YURTSTUDIO'>YURT</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 나의생활이다.</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=soeon'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/1530_mainBrandPick.jpg' alt='브랜드Pick2' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=soeon'>so-eon</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 편안한 통로</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=monotask'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/1531_mainBrandPick.jpg' alt='브랜드Pick3' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=monotask'>Monotask</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 Be a monotasker</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
brand_MainBrandPick+="<li>"
brand_MainBrandPick+="	<div class='pic'>"
brand_MainBrandPick+="	<a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=8colors'><img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/1532_mainBrandPick.jpg' alt='브랜드Pick4' /></a>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<div class='txt'>"
brand_MainBrandPick+="		<p class='brandPdt'><a href='http://www.10x10.co.kr/street/street_brand_sub06.asp?makerid=8colors'>8colors</a></p>"
brand_MainBrandPick+="		<p class='cmt'><em></em><span>디자인은 다양한 컬러이다!</span></p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="</li>"
document.write(brand_MainBrandPick);
