var vCtHtml119 = "<div class='gnb-sub' id='gnb119'>";
vCtHtml119+="		<div class='dept-unit'>";
vCtHtml119+="			<dl>";
vCtHtml119+="				<dt><p><a href='/shopping/category_list.asp?disp=119101'>차/커피/음료 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119101'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml119+="				<dd>";
vCtHtml119+="					<ul class='list-depth'>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119101101'>커피 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119101101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119101102'>원두 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119101102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119101103'>차 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119101103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119101104'>주스/즙 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119101104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119101105'>프리미엄워터 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119101105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119101106'>전통주/주류 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119101106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="					</ul>";
vCtHtml119+="				</dd>";
vCtHtml119+="			</dl>";
vCtHtml119+="		</div>";
vCtHtml119+="		<div class='dept-unit'>";
vCtHtml119+="			<dl>";
vCtHtml119+="				<dt><p><a href='/shopping/category_list.asp?disp=119102'>쨈/꿀/조미료 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml119+="				<dd>";
vCtHtml119+="					<ul class='list-depth'>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119102101'>과일청/시럽 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119102102'>쨈 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119102103'>꿀 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119102104'>소금/설탕/고추장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119102105'>올리브오일/식초 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119102106'>참기름/들기름 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119102107'>수입조미료/소스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119102107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="					</ul>";
vCtHtml119+="				</dd>";
vCtHtml119+="			</dl>";
vCtHtml119+="		</div>";
vCtHtml119+="		<div class='dept-unit'>";
vCtHtml119+="			<dl>";
vCtHtml119+="				<dt><p><a href='/shopping/category_list.asp?disp=119103'>베이커리/베이킹 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119103'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml119+="				<dd>";
vCtHtml119+="					<ul class='list-depth'>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119103101'>파이/케이크 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119103101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119103102'>쿠키/스낵 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119103102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119103103'>도넛/빵 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119103103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119103104'>초콜릿/빼빼로/빵만들... <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119103104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="					</ul>";
vCtHtml119+="				</dd>";
vCtHtml119+="			</dl>";
vCtHtml119+="		</div>";
vCtHtml119+="		<div class='dept-unit'>";
vCtHtml119+="			<dl>";
vCtHtml119+="				<dt><p><a href='/shopping/category_list.asp?disp=119104'>스낵/견과 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119104'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml119+="				<dd>";
vCtHtml119+="					<ul class='list-depth'>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119104101'>견과류/시리얼 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119104101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119104102'>초콜릿 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119104102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119104103'>캔디/카라멜 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119104103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119104104'>요거트/유제품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119104104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="						<li><a href='/shopping/category_list.asp?disp=119104105'>수입과자 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119104105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml119+="					</ul>";
vCtHtml119+="				</dd>";
vCtHtml119+="			</dl>";
vCtHtml119+="		</div>";
vCtHtml119+="		<div class='dept-unit dept-unit-top'>";
vCtHtml119+="			<ul class='list-depth'>";
vCtHtml119+="				<li><p><a href='/shopping/category_list.asp?disp=119105'><b>반조리식품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml119+="				</li>";
vCtHtml119+="				<li><p><a href='/shopping/category_list.asp?disp=119106'><b>신선식품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml119+="				</li>";
vCtHtml119+="				<li><p><a href='/shopping/category_list.asp?disp=119107'><b>전통식품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml119+="				</li>";
vCtHtml119+="				<li><p><a href='/shopping/category_list.asp?disp=119108'><b>헬스/다이어트식품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml119+="				</li>";
vCtHtml119+="				<li><p><a href='/shopping/category_list.asp?disp=119109'><b>BOOK <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp119109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml119+="				</li>";
vCtHtml119+="				<li><p><a href='/shoppingtoday/shoppingchance_saleitem.asp?disp=119109' class='color-red'><b>SALE</b></a></p></li>";
vCtHtml119+="				<li><p><a href='/shoppingtoday/shoppingchance_allevent.asp?disp=119109' class='color-blue'><b>EVENT</b></a></p></li>";
vCtHtml119+="			</ul>";
vCtHtml119+="		</div>";
vCtHtml119+="</div>";
vCtHtml119+="";