var vCtHtml118 = "<div class='gnb-sub' id='gnb118'>";
vCtHtml118+="		<div class='dept-unit'>";
vCtHtml118+="			<dl>";
vCtHtml118+="				<dt><p><a href='/shopping/category_list.asp?disp=118101'>스킨케어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml118+="				<dd>";
vCtHtml118+="					<ul class='list-depth'>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118101101'>토너 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118101102'>에센스/에멀젼 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118101103'>크림/오일 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118101104'>링클/아이케어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118101105'>썬케어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118101106'>스킨케어 세트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118101107'>미스트/마스크 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118101107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="					</ul>";
vCtHtml118+="				</dd>";
vCtHtml118+="			</dl>";
vCtHtml118+="		</div>";
vCtHtml118+="		<div class='dept-unit'>";
vCtHtml118+="			<dl>";
vCtHtml118+="				<dt><p><a href='/shopping/category_list.asp?disp=118102'>바디/헤어케어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml118+="				<dd>";
vCtHtml118+="					<ul class='list-depth'>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102103'>샤워젤 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102102'>바디로션/오일 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102101'>핸드크림/풋크림 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102108'>바디미스트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102104'>바디스크럽 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102105'>쉐이빙/제모케어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102106'>바디케어 세트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118102107'>헤어케어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118102107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="					</ul>";
vCtHtml118+="				</dd>";
vCtHtml118+="			</dl>";
vCtHtml118+="		</div>";
vCtHtml118+="		<div class='dept-unit'>";
vCtHtml118+="			<dl>";
vCtHtml118+="				<dt><p><a href='/shopping/category_list.asp?disp=118103'>비누/입욕제 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118103'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml118+="				<dd>";
vCtHtml118+="					<ul class='list-depth'>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118103106'>비누 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118103106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118103105'>입욕제 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118103105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="					</ul>";
vCtHtml118+="				</dd>";
vCtHtml118+="			</dl>";
vCtHtml118+="		</div>";
vCtHtml118+="		<div class='dept-unit'>";
vCtHtml118+="			<dl>";
vCtHtml118+="				<dt><p><a href='/shopping/category_list.asp?disp=118104'>메이크업 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118104'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml118+="				<dd>";
vCtHtml118+="					<ul class='list-depth'>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118104101'>아이 메이크업 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118104101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118104102'>립 메이크업 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118104102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118104103'>블러셔/하이라이터 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118104103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118104104'>베이스 메이크업 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118104104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="						<li><a href='/shopping/category_list.asp?disp=118104105'>파우더/팩트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118104105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml118+="					</ul>";
vCtHtml118+="				</dd>";
vCtHtml118+="			</dl>";
vCtHtml118+="		</div>";
vCtHtml118+="		<div class='dept-unit dept-unit-top'>";
vCtHtml118+="			<ul class='list-depth'>";
vCtHtml118+="				<li><p><a href='/shopping/category_list.asp?disp=118105'><b>네일/디자인타투 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml118+="				</li>";
vCtHtml118+="				<li><p><a href='/shopping/category_list.asp?disp=118106'><b>클렌저 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml118+="				</li>";
vCtHtml118+="				<li><p><a href='/shopping/category_list.asp?disp=118107'><b>향수 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml118+="				</li>";
vCtHtml118+="				<li><p><a href='/shopping/category_list.asp?disp=118108'><b>뷰티기기/소품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml118+="				</li>";
vCtHtml118+="				<li><p><a href='/shopping/category_list.asp?disp=118109'><b>남성 뷰티 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml118+="				</li>";
vCtHtml118+="				<li><p><a href='/shopping/category_list.asp?disp=118110'><b>다이어트/헬스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118110'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml118+="				</li>";
vCtHtml118+="				<li><p><a href='/shopping/category_list.asp?disp=118111'><b>BOOK <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp118111'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml118+="				</li>";
vCtHtml118+="				<li><p><a href='/shoppingtoday/shoppingchance_saleitem.asp?disp=118111' class='color-red'><b>SALE</b></a></p></li>";
vCtHtml118+="				<li><p><a href='/shoppingtoday/shoppingchance_allevent.asp?disp=118111' class='color-blue'><b>EVENT</b></a></p></li>";
vCtHtml118+="			</ul>";
vCtHtml118+="		</div>";
vCtHtml118+="</div>";
vCtHtml118+="";