var vCtHtml121 = "<div class='gnb-sub' id='gnb121'>";
vCtHtml121+="		<div class='dept-unit'>";
vCtHtml121+="			<dl>";
vCtHtml121+="				<dt><p><a href='/shopping/category_list.asp?disp=121115'>수납/정리 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121115'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml121+="				<dd>";
vCtHtml121+="					<ul class='list-depth'>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121115101'>옷/이불수납 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121115101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121115102'>바구니/박스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121115102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121115103'>아이템정리 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121115103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121115104'>선반/수납장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121115104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121115105'>데스크/책장수납 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121115105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="					</ul>";
vCtHtml121+="				</dd>";
vCtHtml121+="			</dl>";
vCtHtml121+="		</div>";
vCtHtml121+="		<div class='dept-unit'>";
vCtHtml121+="			<dl>";
vCtHtml121+="				<dt><p><a href='/shopping/category_list.asp?disp=121102'>디자인 체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml121+="				<dd>";
vCtHtml121+="					<ul class='list-depth'>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102101'>컴포트체어/암체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102106'>스툴 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102104'>우드체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102105'>패브릭/가죽체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102107'>플라스틱체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102113'>철제체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102113'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102108'>투명체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102109'>바체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102110'>오피스체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102110'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121102102'>빈백소파 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121102102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="					</ul>";
vCtHtml121+="				<a href='/shopping/category_list.asp?disp=121102' class='btn-linkV18 link3'>more <span></span></a>";
vCtHtml121+="				</dd>";
vCtHtml121+="			</dl>";
vCtHtml121+="		</div>";
vCtHtml121+="		<div class='dept-unit'>";
vCtHtml121+="			<dl>";
vCtHtml121+="				<dt><p><a href='/shopping/category_list.asp?disp=121103'>홈오피스가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml121+="				<dd>";
vCtHtml121+="					<ul class='list-depth'>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103101'>책상 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103102'>2인용 책상 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103112'>각도조절/높이조절 책... <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103112'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103103'>오피스세트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103104'>오피스체어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103105'>책장 / 수납장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103106'>서랍장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103108'>캐비넷 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103109'>북선반/벽선반 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121103110'>공간박스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121103110'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="					</ul>";
vCtHtml121+="				<a href='/shopping/category_list.asp?disp=121103' class='btn-linkV18 link3'>more <span></span></a>";
vCtHtml121+="				</dd>";
vCtHtml121+="			</dl>";
vCtHtml121+="		</div>";
vCtHtml121+="		<div class='dept-unit'>";
vCtHtml121+="			<dl>";
vCtHtml121+="				<dt><p><a href='/shopping/category_list.asp?disp=121104'>침실가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml121+="				<dd>";
vCtHtml121+="					<ul class='list-depth'>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104101'>침대세트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104102'>침대 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104103'>매트리스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104104'>화장대 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104110'>거울 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104110'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104105'>협탁 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104106'>옷장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104109'>오픈옷장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104107'>서랍장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="						<li><a href='/shopping/category_list.asp?disp=121104108'>파티션 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121104108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml121+="					</ul>";
vCtHtml121+="				</dd>";
vCtHtml121+="			</dl>";
vCtHtml121+="		</div>";
vCtHtml121+="		<div class='dept-unit dept-unit-top'>";
vCtHtml121+="			<ul class='list-depth'>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121105'><b>거실가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121106'><b>테이블 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121107'><b>주방가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121108'><b>키즈가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121109'><b>1인가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121111'><b>국내 디자이너가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121111'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121112'><b>해외 디자인가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121112'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121110'><b>아웃도어가구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121110'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121113'><b>DIY 가구/도구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121113'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shopping/category_list.asp?disp=121114'><b>BOOK <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp121114'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml121+="				</li>";
vCtHtml121+="				<li><p><a href='/shoppingtoday/shoppingchance_saleitem.asp?disp=121114' class='color-red'><b>SALE</b></a></p></li>";
vCtHtml121+="				<li><p><a href='/shoppingtoday/shoppingchance_allevent.asp?disp=121114' class='color-blue'><b>EVENT</b></a></p></li>";
vCtHtml121+="			</ul>";
vCtHtml121+="		</div>";
vCtHtml121+="</div>";
vCtHtml121+="";