var vCtHtml122 = "<div class='gnb-sub' id='gnb122'>";
vCtHtml122+="		<div class='dept-unit'>";
vCtHtml122+="			<dl>";
vCtHtml122+="				<dt><p><a href='/shopping/category_list.asp?disp=122114'>조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml122+="				<dd>";
vCtHtml122+="					<ul class='list-depth'>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114105'>펜던트 조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114101'>플로어 조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114102'>테이블 조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114110'>무드등/볼조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114110'>H</span> <span class='icoV18 ico-new' >N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114104'>데스크 스탠드 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114103'>메세지 조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114109'>벽조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114106'>레일 조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114107'>천장 조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122114111'>센서등/현관 조명 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122114111'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="					</ul>";
vCtHtml122+="				<a href='/shopping/category_list.asp?disp=122114' class='btn-linkV18 link3'>more <span></span></a>";
vCtHtml122+="				</dd>";
vCtHtml122+="			</dl>";
vCtHtml122+="		</div>";
vCtHtml122+="		<div class='dept-unit'>";
vCtHtml122+="			<dl>";
vCtHtml122+="				<dt><p><a href='/shopping/category_list.asp?disp=122104'>그림 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml122+="				<dd>";
vCtHtml122+="					<ul class='list-depth'>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104114'>태피스트리 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104114'>H</span> <span class='icoV18 ico-new' >N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104103'>식물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104102'>풍경 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104111'>레터링 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104111'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104101'>명화 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104105'>인물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104107'>사물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104104'>동물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104108'>패턴 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122104109'>빈티지 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122104109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="					</ul>";
vCtHtml122+="				<a href='/shopping/category_list.asp?disp=122104' class='btn-linkV18 link3'>more <span></span></a>";
vCtHtml122+="				</dd>";
vCtHtml122+="			</dl>";
vCtHtml122+="		</div>";
vCtHtml122+="		<div class='dept-unit'>";
vCtHtml122+="			<dl>";
vCtHtml122+="				<dt><p><a href='/shopping/category_list.asp?disp=122101'>시계 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122101'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml122+="				<dd>";
vCtHtml122+="					<ul class='list-depth'>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122101101'>벽시계 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122101101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122101103'>탁상시계 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122101103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122101104'>알람시계 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122101104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122101105'>양면시계 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122101105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122101106'>그래픽시계 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122101106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122101107'>타이머/스톱워치 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122101107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="					</ul>";
vCtHtml122+="				</dd>";
vCtHtml122+="			</dl>";
vCtHtml122+="		</div>";
vCtHtml122+="		<div class='dept-unit'>";
vCtHtml122+="			<dl>";
vCtHtml122+="				<dt><p><a href='/shopping/category_list.asp?disp=122111'>식물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122111'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml122+="				<dd>";
vCtHtml122+="					<ul class='list-depth'>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122111105'>공기정화식물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122111105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122111108'>수경재배식물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122111108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122111106'>미니식물/테라리움 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122111106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122111109'>중대형식물 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122111109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122111115'>가드닝 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122111115'>H</span> <span class='icoV18 ico-new' >N</span></a></li>";
vCtHtml122+="						<li><a href='/shopping/category_list.asp?disp=122111116'>화분 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122111116'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml122+="					</ul>";
vCtHtml122+="				</dd>";
vCtHtml122+="			</dl>";
vCtHtml122+="		</div>";
vCtHtml122+="		<div class='dept-unit dept-unit-top'>";
vCtHtml122+="			<ul class='list-depth'>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122102'><b>조화 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122115'><b>플라워 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122115'>H</span> <span class='icoV18 ico-new' >N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122105'><b>캔들/인센스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122106'><b>디퓨저/스프레이 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122106'>H</span> <span class='icoV18 ico-new' >N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122103'><b>액자 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122110'><b>월데코/스티커 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122110'>H</span> <span class='icoV18 ico-new' >N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122107'><b>홈파티 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122109'><b>DIY/데코소품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122109'>H</span> <span class='icoV18 ico-new' >N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122113'><b>메리크리스마스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122113'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shopping/category_list.asp?disp=122112'><b>BOOK <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp122112'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml122+="				</li>";
vCtHtml122+="				<li><p><a href='/shoppingtoday/shoppingchance_saleitem.asp?disp=122112' class='color-red'><b>SALE</b></a></p></li>";
vCtHtml122+="				<li><p><a href='/shoppingtoday/shoppingchance_allevent.asp?disp=122112' class='color-blue'><b>EVENT</b></a></p></li>";
vCtHtml122+="			</ul>";
vCtHtml122+="		</div>";
vCtHtml122+="</div>";
vCtHtml122+="";