var vCtHtml101 = "<div class='gnb-sub' id='gnb101'>";
vCtHtml101+="		<div class='dept-unit'>";
vCtHtml101+="			<dl>";
vCtHtml101+="				<dt><p><a href='/shopping/category_list.asp?disp=101102'>다이어리/플래너 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101102'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml101+="				<dd>";
vCtHtml101+="					<ul class='list-depth'>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101102101'>다이어리 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101102101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101102102'>오거나이저 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101102102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101102103'>스케쥴러/플래너 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101102103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101102104'>캘린더 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101102104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="					</ul>";
vCtHtml101+="				</dd>";
vCtHtml101+="			</dl>";
vCtHtml101+="		</div>";
vCtHtml101+="		<div class='dept-unit'>";
vCtHtml101+="			<dl>";
vCtHtml101+="				<dt><p><a href='/shopping/category_list.asp?disp=101103'>노트/메모지 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml101+="				<dd>";
vCtHtml101+="					<ul class='list-depth'>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103101'>베이직 노트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103102'>하드커버 노트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103111'>바인더/6공 노트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103111'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103103'>스프링 노트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103104'>포켓노트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103105'>독서노트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103106'>노트패드 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103107'>수첩 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103108'>메모지 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101103109'>점착메모지 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101103109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="					</ul>";
vCtHtml101+="				<a href='/shopping/category_list.asp?disp=101103' class='btn-linkV18 link3'>more <span></span></a>";
vCtHtml101+="				</dd>";
vCtHtml101+="			</dl>";
vCtHtml101+="		</div>";
vCtHtml101+="		<div class='dept-unit'>";
vCtHtml101+="			<dl>";
vCtHtml101+="				<dt><p><a href='/shopping/category_list.asp?disp=101107'>데코레이션 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml101+="				<dd>";
vCtHtml101+="					<ul class='list-depth'>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107101'>스탬프 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107102'>스티커 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107103'>테이프/다이모 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107107'>테이프 브랜드샵 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107104'>모양펀치 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107105'>선물 포장 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107106'>장식오너먼트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107108'>포스터 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101107109'>뱃지/와펜 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101107109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="					</ul>";
vCtHtml101+="				</dd>";
vCtHtml101+="			</dl>";
vCtHtml101+="		</div>";
vCtHtml101+="		<div class='dept-unit'>";
vCtHtml101+="			<dl>";
vCtHtml101+="				<dt><p><a href='/shopping/category_list.asp?disp=101106'>포토앨범/레코드북 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml101+="				<dd>";
vCtHtml101+="					<ul class='list-depth'>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106101'>앨범 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106102'>미니앨범 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106103'>포토박스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106104'>티켓/영화앨범 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106105'>출산/임신앨범 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106106'>스크랩북 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106107'>기타 레코드 북 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="						<li><a href='/shopping/category_list.asp?disp=101106108'>인화 포토북/동영상 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101106108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml101+="					</ul>";
vCtHtml101+="				</dd>";
vCtHtml101+="			</dl>";
vCtHtml101+="		</div>";
vCtHtml101+="		<div class='dept-unit dept-unit-top'>";
vCtHtml101+="			<ul class='list-depth'>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101104'><b>필기류/펜 케이스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101105'><b>카드/편지/봉투 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101110'><b>파일링/바인더 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101110'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101108'><b>오피스 용품 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101108'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101109'><b>데스크 정리/보관 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101101'><b>해외디자인문구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101112'><b>캐릭터 문구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101112'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101111'><b>미술도구 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101111'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shopping/category_list.asp?disp=101113'><b>BOOK <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp101113'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml101+="				</li>";
vCtHtml101+="				<li><p><a href='/shoppingtoday/shoppingchance_saleitem.asp?disp=101113' class='color-red'><b>SALE</b></a></p></li>";
vCtHtml101+="				<li><p><a href='/shoppingtoday/shoppingchance_allevent.asp?disp=101113' class='color-blue'><b>EVENT</b></a></p></li>";
vCtHtml101+="			</ul>";
vCtHtml101+="		</div>";
vCtHtml101+="</div>";
vCtHtml101+="";