var vCtHtml117 = "<div class='gnb-sub' id='gnb117'>";
vCtHtml117+="		<div class='dept-unit'>";
vCtHtml117+="			<dl>";
vCtHtml117+="				<dt><p><a href='/shopping/category_list.asp?disp=117101'>여성 아우터 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117101'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml117+="				<dd>";
vCtHtml117+="					<ul class='list-depth'>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117101102'>코트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117101102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117101104'>점퍼 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117101104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117101103'>야상 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117101103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117101101'>자켓 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117101101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117101105'>패딩 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117101105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117101106'>레인코트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117101106'>H</span> <span class='icoV18 ico-new' >N</span></a></li>";
vCtHtml117+="					</ul>";
vCtHtml117+="				</dd>";
vCtHtml117+="			</dl>";
vCtHtml117+="		</div>";
vCtHtml117+="		<div class='dept-unit'>";
vCtHtml117+="			<dl>";
vCtHtml117+="				<dt><p><a href='/shopping/category_list.asp?disp=117102'>여성 드레스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml117+="				<dd>";
vCtHtml117+="					<ul class='list-depth'>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102102'>롱/미디 원피스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102101'>미니 원피스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102107'>레이어드 원피스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102103'>민소매 원피스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102104'>정장 원피스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102104'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102109'>생활한복 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102109'>H</span> <span class='icoV18 ico-new' >N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102105'>니트 원피스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117102108'>셀프웨딩 드레스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117102108'>H</span> <span class='icoV18 ico-new' >N</span></a></li>";
vCtHtml117+="					</ul>";
vCtHtml117+="				</dd>";
vCtHtml117+="			</dl>";
vCtHtml117+="		</div>";
vCtHtml117+="		<div class='dept-unit'>";
vCtHtml117+="			<dl>";
vCtHtml117+="				<dt><p><a href='/shopping/category_list.asp?disp=117103'>여성 상의 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117103'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml117+="				<dd>";
vCtHtml117+="					<ul class='list-depth'>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117103101'>티셔츠 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117103101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117103103'>니트/베스트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117103103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117103104'>가디건 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117103104'>H</span> <span class='icoV18 ico-new' >N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117103102'>셔츠/블라우스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117103102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="					</ul>";
vCtHtml117+="				</dd>";
vCtHtml117+="			</dl>";
vCtHtml117+="		</div>";
vCtHtml117+="		<div class='dept-unit'>";
vCtHtml117+="			<dl>";
vCtHtml117+="				<dt><p><a href='/shopping/category_list.asp?disp=117104'>여성 하의 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117104'> H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></p></dt>";
vCtHtml117+="				<dd>";
vCtHtml117+="					<ul class='list-depth'>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117104101'>스커트 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117104101'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117104102'>팬츠 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117104102'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="						<li><a href='/shopping/category_list.asp?disp=117104103'>레깅스 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117104103'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></a></li>";
vCtHtml117+="					</ul>";
vCtHtml117+="				</dd>";
vCtHtml117+="			</dl>";
vCtHtml117+="		</div>";
vCtHtml117+="		<div class='dept-unit dept-unit-top'>";
vCtHtml117+="			<ul class='list-depth'>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117105'><b>남성 아우터 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117105'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117106'><b>남성 상의 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117106'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117107'><b>남성 하의 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117107'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117109'><b>이지웨어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117109'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117108'><b>비치웨어 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117108'>H</span> <span class='icoV18 ico-new' >N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117110'><b>양말 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117110'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117111'><b>디자이너 패션 <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117111'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117116'><b>#SELF WEDDING <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117116'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shopping/category_list.asp?disp=117112'><b>BOOK <span class='icoV18 ico-hot' style='display:none;' id='tophotdisp117112'>H</span> <span class='icoV18 ico-new' style='display:none;'>N</span></b></a></p>";
vCtHtml117+="				</li>";
vCtHtml117+="				<li><p><a href='/shoppingtoday/shoppingchance_saleitem.asp?disp=117112' class='color-red'><b>SALE</b></a></p></li>";
vCtHtml117+="				<li><p><a href='/shoppingtoday/shoppingchance_allevent.asp?disp=117112' class='color-blue'><b>EVENT</b></a></p></li>";
vCtHtml117+="			</ul>";
vCtHtml117+="		</div>";
vCtHtml117+="</div>";
vCtHtml117+="";